version: "3.8"
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
      POSTGRES_DB: inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  product-service:
    build: ./product-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://postgres:5432/products
      QUARKUS_DATASOURCE_USERNAME: product_user
      QUARKUS_DATASOURCE_PASSWORD: product_password
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      QUARKUS_SMALLRYE_REACTIVE_MESSAGING_RABBITMQ_HOSTS: rabbitmq:5672

  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory
      QUARKUS_DATASOURCE_USERNAME: inventory_user
      QUARKUS_DATASOURCE_PASSWORD: inventory_password
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      QUARKUS_SMALLRYE_REACTIVE_MESSAGING_RABBITMQ_HOSTS: rabbitmq:5672

volumes:
  postgres_data: